### ISSUE TITLE
Repo Structured Incorrectly

### ISSUE THREAD

**Issue by Qwerty-Space** [fuzzydragon/Powercord-Blocked-User-Remover#1]
Hi,

I've cloned this plugin into my plugins folder, but it doesn't seem to be installed

**Comment by Qwerty-Space** [comment]
Looks like I have to clone and manually copy the pest folder. Why have you done it like this, instead of the powercord standard?

See these repos as an example:
https://github.com/jaimeadf/who-reacted
https://github.com/cyyynthia/total-members

**Comment by fuzzydragon** [comment]
Hello. This is because I structure of all my repos like this.

**Comment by vdsk** [comment]
https://github.com/vdsk/Powercord-Blocked-User-Remover I made a fork that fixes the issue.
